apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_PASSWORD: bXlwYXNzd29yZA==   # "mypassword" base64 ile encode edildi
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=  # "rootpass" base64 ile encode edildi
